run:
  timeout: 5m
  modules-download-mode: mod

linters:
  enable:
    - goimports
    - revive
    - govet
    - staticcheck
    - errcheck
    - paralleltest
    - nilnil
    - misspell

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  goimports:
    local-prefixes: github.com/EpicStep/clickhouse-go-rows-utils
  revive:
    enable-all-rules: true
    rules:
      - name: var-naming
        disabled: true
      - name: line-length-limit
        disabled: true
      - name: function-length
        disabled: true
      - name: add-constant
        disabled: true
